/* tslint:disable */
/* eslint-disable */
/**
 * eKYC API
 * An API for eKYC prototyping
 *
 * The version of the OpenAPI document: v2
 * Contact: opensource-codeofconduct@amazon.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

